name: Build and deploy app

on:
  push:
    branches:
      - '**/*'

jobs:
  build:
    name: Build
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy app
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: rg-bjo-test-01
          containerAppName: ca-bjo-test-01
          acrName: brightstraining24fall.azurecr.io
          imageToDeploy: brightstraining24fall.azurecr.io/bjorn/dotnetapi:latest
